services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - msg-data:/data/db
  docker-messages:
    image: 970113208363.dkr.ecr.us-east-2.amazonaws.com/docker-messages:latest
    depends_on:
      - mongodb
    ports:
      - 3000:3000
volumes:
  msg-data:
    driver: local
